### ISSUE TITLE
Add example on order impact on @protected

### ISSUE THREAD

**Issue by rubensworks** [w3c/json-ld-bp#2]
Following the discussion in https://github.com/w3c/json-ld-syntax/issues/153, it would be good to add an example to the BP document of non-trivial `@protected` usage that does _not_ throw an error.

The following (error-throwing) example is present in the syntax spec:

```json
{
  "@context": [
    {
      "@version": 1.1,
      "Person": "http://schema.org/Person",
      "knows": "http://schema.org/knows",
      "name": {
        "@id": "http://schema.org/name",
        "@protected": true
      }
    },
    {
      "name": "this_attempt_to_override_name_will_fail"
    }
  ]
}
```

The following would be relevant to add as an example that does _not_ throw an error, even though there is a term override happening:

```json
{
  "@context": [
    {
      "name": "this_attempt_to_override_name_will_fail"
    },
    {
      "@version": 1.1,
      "Person": "http://schema.org/Person",
      "knows": "http://schema.org/knows",
      "name": {
        "@id": "http://schema.org/name",
        "@protected": true
      }
    }
  ]
}
```

**Comment by BigBlueHat** [comment]
Isn't this just the normal inheritance/overriding pattern then? Also, if the first "name" actually does get overridden (in your second example) it's value should change. 😃

**Comment by rubensworks** [comment]
> Isn't this just the normal inheritance/overriding pattern then?

Yes, you're right.

The only reason for adding this example would be to clarify that `@protected` can –next to creating a brand new protected term– also be used while redefining an (unprotected) term.

This was an open question for me after reading the section on `@protected` in the spec, so it's possible that other people may have the same question.

**Comment by pchampin** [comment]
> so it's possible that other people may have the same question.

granted. But on the other hand, I'm concerned that too many examples would be counter productive, making the spec harder to read...

**Comment by gkellogg** [comment]
Usually, test cases serve to flesh out corner cases; although not visible in the spec, they do serve a good purpose for describing such behavior.

**Comment by iherman** [comment]
There may be one reason why this should be put into the BP document: the text does emphasize in §3.4 JSON array should assume that values in an array should be assumed as unordered. However, the value of `@context` is different: order of contexts _does count_, and this is a good (albeit possibly a bit complex) example.

**Comment by ajs6f** [comment]
It shouldn't be too hard to develop an isolated example showing two simple contexts interact that way. I think it's a very good idea to show it, and not just tell people about it in the spec.

**Comment by ajs6f** [comment]
Is the desire here to feature an example with two contexts (as per @rubensworks' example above) that do and don't successfully override a definition, based on the ordering question? Is @rubensworks' example (perhaps with a different vocabulary) meet for that purpose immediately?

**Comment by iherman** [comment]
This issue was discussed in [a meeting](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2020/2020-02-07-json-ld#section4-3).

- No actions or resolutions
<details><summary><i class="differentiate">View the transcript</i></summary>
issue on protected<br/>
Benjamin Young: <a href="https://github.com/w3c/json-ld-bp/issues/2">https://github.com/w3c/json-ld-bp/issues/2</a><br/>
Ruben Taelman: this issue was created to clarify that for protection of terms that order is important<br/>
… in the first snippet, the overriding of the term would result in a failure, but if you reverse the contexts, the failure doesn’t happen<br/>
… so clarify order is important<br/>
Benjamin Young: where you introduce the protection has an effect<br/>
… protected in the middle of the list is different from at the end<br/>
… anyone want to help on this?<br/>
… dlehn did you work on this?<br/>
… Or was it more dlongley?<br/>
David I. Lehn: I’d have to take a look. Partly involved but not core.<br/>
Ruben Taelman: I can also help<br/>
Benjamin Young: that woudl be super. I can assign to you for now<br/>
… thank you very much<br/>
… streaming got some love, so lets look at #13<br/>
</details>
