### ISSUE TITLE
Question about good practice for @id

### ISSUE THREAD

**Issue by cristianvasquez** [w3c/json-ld-bp#7]
Hello,

I'm looking at this document:  https://json-ld.org/spec/latest/json-ld-api-best-practices/

Where Best Practice 8, "Identify objects with a unique identifier," says:

'Entities described in JSON objects often describe web resources having a URL; entity descriptions SHOULD use an identifier uniquely identifying that entity. In this case, using the resource location as the identity of the object is consistent with this practice.'

This mechanism allows a client to follow, without effort, links to other entities in the Web.

But sometimes @id have a context on it like in:

```
{
  "@context": {
    ...
    "image": { "@id": "schema:image", "@type": "@id"},
    ...
  }
}
```

In this case, the client needs to be smart enough to build the URL to follow links.

Question: could be considered a good practice to provide URLs in @id when possible?

**Comment by pchampin** [comment]
> I just realized that my original question should have been: when to use each application/ld+json profile? ( expanded, compacted, and flattened)

In general, there are 2 ways to consume JSON-LD data.

The first way is when clients are *aware* that the data is JSON-LD (rather than plain JSON). They are therefore supposed to know about the JSON-LD API, and can "juggle" between the different representations (compact, expanded, flat) depending on their needs. In particular, they would rely on expansion to resolve compact IRIs (`foo:bar`) into absolute IRIs.

The second way is when clients consider JSON-LD as plain JSON. These clients expect a compact form, that complies with a given "format" (possibly described with a JSON-schema or a similar specification). These kinds of clients are supposed to have the format's semantics built-in.

So to answer your question about best practices: if you only target the first kind of clients, then compact IRIs should not be a problem. If you target both kinds of clients, then your compact form will have to comply with the JSON-based format expected by the 2nd kind. The vast majority of such formats do *not* use compact IRIs, so indeed, that will generally mean using absolute IRIs. But this is dictated by the format to which your JSON-LD context aims to align, not by JSON-LD itself.

**Comment by iherman** [comment]
I believe that the duality described in https://github.com/w3c/json-ld-bp/issues/7#issuecomment-513214503 by @pchampin is expressed as an explicit issue: namely #19.

@pchampin @cristianvasquez is it o.k. to close this issue and let #19 take its course?

**Comment by pchampin** [comment]
Ok for me, but this is @cristianvasquez's issue :)

**Comment by cristianvasquez** [comment]
Thanks ! :)
